# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [1]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [2]:
s = 0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s += i

print('平均成績:',s/len(grades))

平均成績: 74.8


### 【示範】陣列導向

In [5]:
grades = [77, 85, 56, 90, 66]
arr = np.array(grades)
print(arr.mean())

74.8


最大值

In [6]:
arr.max()

90

標準差

In [7]:
arr.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [8]:
prices = [1096.95, 596.95, 896.95]
usd2twd = 31.71
twdprice = []
for i in prices:
    twdprice.append(i * usd2twd)

print(twdprice)


[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [10]:
prices = [1096.95, 596.95, 896.95]
prices = np.array(prices)
usd2twd = 31.71
prices * usd2twd

array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [12]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])


這還不是我們要的最終成績啊!

In [13]:
grades * weights

array([17. , 24.5, 36. ])

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [14]:
grades_weights = grades * weights
grades_weights.sum()

77.5

### 【技巧】 一行完成成績計算

In [18]:
np.dot(grades, weights)


77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [19]:
A = np.random.rand(50)
A

array([0.27638704, 0.97331946, 0.77193851, 0.01596437, 0.95157347,
       0.89054741, 0.65826135, 0.32194287, 0.7394431 , 0.49760748,
       0.72845173, 0.79384809, 0.17970563, 0.23196705, 0.33473577,
       0.44481811, 0.07335755, 0.17044562, 0.72133226, 0.88809774,
       0.61340199, 0.9516713 , 0.88254071, 0.09974258, 0.47091289,
       0.73748185, 0.43266947, 0.7353877 , 0.98110914, 0.23468484,
       0.74337637, 0.43005668, 0.37919373, 0.68991867, 0.74420789,
       0.79599655, 0.50059661, 0.45769112, 0.7739082 , 0.77580818,
       0.99401658, 0.6533474 , 0.85987006, 0.68951922, 0.49607256,
       0.0843035 , 0.31694093, 0.58037763, 0.24771368, 0.84797892])

### 【技巧】 檢查 A 的 `shape`

In [20]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [23]:
A.shape = (5,10)
A

array([[0.27638704, 0.97331946, 0.77193851, 0.01596437, 0.95157347,
        0.89054741, 0.65826135, 0.32194287, 0.7394431 , 0.49760748],
       [0.72845173, 0.79384809, 0.17970563, 0.23196705, 0.33473577,
        0.44481811, 0.07335755, 0.17044562, 0.72133226, 0.88809774],
       [0.61340199, 0.9516713 , 0.88254071, 0.09974258, 0.47091289,
        0.73748185, 0.43266947, 0.7353877 , 0.98110914, 0.23468484],
       [0.74337637, 0.43005668, 0.37919373, 0.68991867, 0.74420789,
        0.79599655, 0.50059661, 0.45769112, 0.7739082 , 0.77580818],
       [0.99401658, 0.6533474 , 0.85987006, 0.68951922, 0.49607256,
        0.0843035 , 0.31694093, 0.58037763, 0.24771368, 0.84797892]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [24]:
A.reshape(10,5)

array([[0.27638704, 0.97331946, 0.77193851, 0.01596437, 0.95157347],
       [0.89054741, 0.65826135, 0.32194287, 0.7394431 , 0.49760748],
       [0.72845173, 0.79384809, 0.17970563, 0.23196705, 0.33473577],
       [0.44481811, 0.07335755, 0.17044562, 0.72133226, 0.88809774],
       [0.61340199, 0.9516713 , 0.88254071, 0.09974258, 0.47091289],
       [0.73748185, 0.43266947, 0.7353877 , 0.98110914, 0.23468484],
       [0.74337637, 0.43005668, 0.37919373, 0.68991867, 0.74420789],
       [0.79599655, 0.50059661, 0.45769112, 0.7739082 , 0.77580818],
       [0.99401658, 0.6533474 , 0.85987006, 0.68951922, 0.49607256],
       [0.0843035 , 0.31694093, 0.58037763, 0.24771368, 0.84797892]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [26]:
A.ravel()

array([0.27638704, 0.97331946, 0.77193851, 0.01596437, 0.95157347,
       0.89054741, 0.65826135, 0.32194287, 0.7394431 , 0.49760748,
       0.72845173, 0.79384809, 0.17970563, 0.23196705, 0.33473577,
       0.44481811, 0.07335755, 0.17044562, 0.72133226, 0.88809774,
       0.61340199, 0.9516713 , 0.88254071, 0.09974258, 0.47091289,
       0.73748185, 0.43266947, 0.7353877 , 0.98110914, 0.23468484,
       0.74337637, 0.43005668, 0.37919373, 0.68991867, 0.74420789,
       0.79599655, 0.50059661, 0.45769112, 0.7739082 , 0.77580818,
       0.99401658, 0.6533474 , 0.85987006, 0.68951922, 0.49607256,
       0.0843035 , 0.31694093, 0.58037763, 0.24771368, 0.84797892])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [32]:
np.zeros(10)
np.zeros((20,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

### 【技巧】 都是 1 的 array

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [37]:
x = np.linspace(0,10,50)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### 【技巧】`range` 的 array 版

就是 `arange`。

In [38]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [40]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [43]:
A.sum(axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [44]:
A.sum(axis=1)

array([10, 35])

### 【提示】當然也有可能全部算

In [46]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [47]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [48]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [49]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [50]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [52]:
L = L[L>0]
L

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [55]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x[2:5]

array([2, 3, 4])

### 【技巧】2維陣列切法

記得先列後行!

In [59]:
x = x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [61]:
x[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [65]:
x[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [67]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [68]:
X = np.c_[x,y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
Y = np.r_[x,y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [70]:
X[:,0]

array([1, 2, 3, 4])